### ISSUE TITLE
any appetite for iscsi tools image?

### ISSUE THREAD

**Issue by dlasky** [nberlee/extensions#2]
Just trying to get replicated storage going on my RK1s, but I know this is intended to be a short lived fork, so understand if its not useful/feasible.

Thanks for the great work!!!

https://github.com/nberlee/extensions/blob/f5b32470e639c124c2b76f6a4b268015fe1e7b5d/Makefile#L54

**Comment by nberlee** [comment]
Oh, I didn't see your issue, until now. Happy to add it as a extension, but you can use the siderolabs I think as it does not involve kernel modules.

Using the (depreciated, but still working) extensions in the machine config manifest: 
```
machine:
  install:
     extensions:
         - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
 ```
 
 Make sure to run talosctl upgrade afterwards
